/* ecrypt-sync.c */

/* *** Please do not edit this file. *** */

#include "ecrypt-sync.h"

#ifdef RABBIT_USES_DEFAULT_ALL_IN_ONE

/*
 * Default implementation of all-in-one encryption/decryption of
 * (short) packets.
 */

#ifdef RABBIT_HAS_SINGLE_PACKET_FUNCTION

void RABBIT_process_packet(
  int action,
  RABBIT_ctx* ctx,
  const u8* iv,
  const u8* input,
  u8* output,
  u32 msglen)
{
  RABBIT_ivsetup(ctx, iv);

#ifdef RABBIT_HAS_SINGLE_BYTE_FUNCTION
  RABBIT_process_bytes(action, ctx, input, output, msglen);
#else
  if (action == 0)
    RABBIT_encrypt_bytes(ctx, input, output, msglen);
  else
    RABBIT_decrypt_bytes(ctx, input, output, msglen);
#endif
}

#else

void RABBIT_encrypt_packet(
  RABBIT_ctx* ctx,
  const u8* iv,
  const u8* plaintext,
  u8* ciphertext,
  u32 msglen)
{
  RABBIT_ivsetup(ctx, iv);
  RABBIT_encrypt_bytes(ctx, plaintext, ciphertext, msglen);
}

void RABBIT_decrypt_packet(
  RABBIT_ctx* ctx,
  const u8* iv,
  const u8* ciphertext,
  u8* plaintext,
  u32 msglen)
{
  RABBIT_ivsetup(ctx, iv);
  RABBIT_decrypt_bytes(ctx, ciphertext, plaintext, msglen);
}

#endif

#endif
